springdoc:
  packages-to-scan: com.righttek.es.empresa.controller
  pathsToMatch: /v1, /api/es/empresa/**

# CONECCION A BASE DE DATOS
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/TEST_GOTALENT
    username: postgres
    password: Admin040617
    driver-class-name: org.postgresql.Driver
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
# SERVICIOS A CONSUMIR
uri:
  nomina-externa: "http://rgt-us-nominaexterna:8082"
