# CONECCION A BASE DE DATOS
spring:
  datasource:
    #url: jdbc:postgresql://${SERVER_POSTGRES}:5431/TEST_GOTALENT
    url: jdbc:postgresql://localhost:5433/TEST_GOTALENT
    username: postgres
    password: Admin040617
    driver-class-name: org.postgresql.Driver
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        lob:
          non_contextual_creation: true

# ESPECIFICACIONES DE KAFKA
  kafka:
    #bootstrap-servers: ${SERVER_KAFKA}:${PORT_KAFKA}
    bootstrap-servers: 10.35.2.65:9092
    consumer:
      group-id: myGroup
