server:
  port: 8079
  
  
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.132:5433/TEST_GOTALENT
    username: postgres
    password: Admin040617
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        lob:
         non_contextual_creational: true
         
  kafka:
    bootstrap-servers: kafka:9093
    consumer:
      group-id: myGroup 
