server:
  port: 8094

# ESPECIFICACIONES DE KAFKA
spring:
  kafka:
    bootstrap-servers: 192.168.100.67:9092
    consumer:
      group-id: myGroup

# SERVICIOS A CONSUMIR
uri:
  nomina-externa: "http://192.168.100.67:8082"
  esfuerzo-laboral: "http://192.168.100.67:8073"
  marcacion: "http://192.168.100.67:8071"